"""
kroniqo-agent/setup_flow.py

Conversational setup — Kroniqo walks you through configuration
and writes everything to a .env file automatically.

Run once: python setup_flow.py
Then:     python agent.py  (picks up config automatically)
          python telegram_bot.py  (picks up telegram token automatically)
"""

import os
import sys
import requests
from pathlib import Path

CONFIG_FILE = Path(__file__).parent / ".env"


def load_env():
    """Load existing .env if present."""
    config = {}
    if CONFIG_FILE.exists():
        for line in CONFIG_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                config[k.strip()] = v.strip()
    return config


def save_env(config: dict):
    lines = ["# Kroniqo configuration — auto-generated by setup_flow.py", ""]
    for k, v in config.items():
        lines.append(f"{k}={v}")
    CONFIG_FILE.write_text("\n".join(lines))
    print(f"\n  Saved to {CONFIG_FILE}")


def test_groq(key: str) -> bool:
    try:
        r = requests.post(
            "https://api.groq.com/openai/v1/chat/completions",
            headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
            json={"model": "llama-3.3-70b-versatile", "max_tokens": 10,
                  "messages": [{"role": "user", "content": "hi"}]},
            timeout=10
        )
        return r.status_code == 200
    except:
        return False


def test_gemini(key: str) -> bool:
    try:
        r = requests.post(
            "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
            headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
            json={"model": "gemini-2.0-flash", "max_tokens": 10,
                  "messages": [{"role": "user", "content": "hi"}]},
            timeout=10
        )
        return r.status_code == 200
    except:
        return False


def test_telegram(token: str) -> dict | None:
    try:
        r = requests.get(f"https://api.telegram.org/bot{token}/getMe", timeout=10)
        if r.status_code == 200:
            return r.json().get("result")
    except:
        pass
    return None


def send_telegram_message(token: str, chat_id: str, text: str) -> bool:
    try:
        r = requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat_id, "text": text},
            timeout=10
        )
        return r.status_code == 200
    except:
        return False


def get_telegram_chat_id(token: str) -> str | None:
    """Get chat_id from the most recent message sent to the bot."""
    try:
        r = requests.get(f"https://api.telegram.org/bot{token}/getUpdates", timeout=10)
        if r.status_code == 200:
            updates = r.json().get("result", [])
            if updates:
                return str(updates[-1]["message"]["chat"]["id"])
    except:
        pass
    return None


def setup():
    print("\n╔══════════════════════════════════════╗")
    print("║   Kroniqo Setup                      ║")
    print("╚══════════════════════════════════════╝")
    print("I'll walk you through connecting your API keys.\n")

    config = load_env()

    # Apply existing config to environment
    for k, v in config.items():
        os.environ[k] = v

    if config:
        print(f"Found existing config at {CONFIG_FILE}")
        existing = [k for k in config if config[k]]
        print(f"Already configured: {', '.join(existing)}\n")
        redo = input("Reconfigure from scratch? (y/n) [n]: ").strip().lower()
        if redo != "y":
            print("Using existing config. Run agent.py or telegram_bot.py to start.\n")
            return

    print("Step 1: LLM Backend")
    print("─────────────────────────────────────")
    print("Recommended: Groq (free, fast — console.groq.com)")
    print("Alternative: Gemini (free, more volume — aistudio.google.com)\n")

    groq_key = input("Paste your GROQ_API_KEY (or press Enter to skip): ").strip()
    if groq_key:
        print("  Testing Groq key...", end=" ", flush=True)
        if test_groq(groq_key):
            print("✓ Connected")
            config["GROQ_API_KEY"] = groq_key
        else:
            print("✗ Failed — key may be invalid")
            groq_key = ""

    gemini_key = input("Paste your GEMINI_API_KEY (or press Enter to skip): ").strip()
    if gemini_key:
        print("  Testing Gemini key...", end=" ", flush=True)
        if test_gemini(gemini_key):
            print("✓ Connected")
            config["GEMINI_API_KEY"] = gemini_key
        else:
            print("✗ Failed — key may be invalid")

    if not groq_key and not config.get("GROQ_API_KEY") and not config.get("GEMINI_API_KEY"):
        print("\n  No backend configured — you need at least one key to run Kroniqo.")
        print("  Get Groq free key at: console.groq.com")
        return

    print("\nStep 2: Telegram Bot (optional)")
    print("─────────────────────────────────────")
    print("Get a bot token from @BotFather on Telegram → /newbot\n")

    tg_token = input("Paste your TELEGRAM_BOT_TOKEN (or press Enter to skip): ").strip()
    chat_id = None

    if tg_token:
        print("  Verifying token...", end=" ", flush=True)
        bot_info = test_telegram(tg_token)
        if bot_info:
            print(f"✓ Bot found: @{bot_info.get('username')}")
            config["TELEGRAM_BOT_TOKEN"] = tg_token

            print("\n  To get your chat ID:")
            print(f"  1. Open Telegram and message @{bot_info.get('username')}")
            print("  2. Send any message (e.g. 'hello')")
            input("  3. Press Enter when done...")

            chat_id = get_telegram_chat_id(tg_token)
            if chat_id:
                print(f"  ✓ Chat ID found: {chat_id}")
                config["TELEGRAM_CHAT_ID"] = chat_id
            else:
                chat_id = input("  Could not auto-detect. Paste your chat ID manually: ").strip()
                if chat_id:
                    config["TELEGRAM_CHAT_ID"] = chat_id
        else:
            print("✗ Invalid token")

    # Save config
    save_env(config)

    # Apply to current environment
    for k, v in config.items():
        os.environ[k] = v

    # Send Telegram confirmation
    if tg_token and chat_id and bot_info:
        print("\n  Sending you a Telegram message...", end=" ", flush=True)
        msg = (
            f"Kroniqo is configured and ready.\n\n"
            f"Backend: {'Groq' if config.get('GROQ_API_KEY') else 'Gemini'}\n"
            f"Commands: /ask /biography /debug /outcome /backends\n\n"
            f"I'm starting fresh — no decisions made yet. Start asking me things."
        )
        if send_telegram_message(tg_token, chat_id, msg):
            print("✓ Message sent")
        else:
            print("✗ Could not send — check chat ID")

    print("\n╔══════════════════════════════════════╗")
    print("║   Setup Complete                     ║")
    print("╚══════════════════════════════════════╝")
    print("\nTo start CLI agent:     python kroniqo-agent/agent.py")
    if config.get("TELEGRAM_BOT_TOKEN"):
        print("To start Telegram bot:  python kroniqo-agent/telegram_bot.py")
    print()


if __name__ == "__main__":
    setup()
